#include <catch2/catch.hpp>

#include "db.hpp"

TEST_CASE("db", "[db]")
{
    Db db({"AGAT", "AATG", "TATC"});
    db.insert("Alice", {5, 2, 8});
    db.insert("Bob", {3, 7, 4});
    db.insert("Charlie", {6, 1, 5});

    REQUIRE(db.numStrs() == 3);
    REQUIRE(db.findMatch("AGACGGGTTACCATGACTATCTATCTATCTATCTATCTATCTATCTATCACGTACGTACGTATCGAGATAGATAGATAGATAGATCCTCGACT"
                         "TCGATCGCAATGAATGCCAATAGACAAAA") == "Alice");
    REQUIRE(db.findMatch("AACCCTGCGCGCGCGCGATCTATCTATCTATCTATCCAGCATTAGCTAGCATCAAGATAGATAGATGAATTTCGAAATGAATGAATGAATGAA"
                         "TGAATGAATG") == "Bob");
    REQUIRE(db.findMatch("CCAGATAGATAGATAGATAGATAGATGTCACAGGGATGCTGAGGGCTGCTTCGTACGTACTCCTGATTTCGGGGATCGCTGACACTAATGCGT"
                         "GCGAGCGGATCGATCTCTATCTATCTATCTATCTATCCTATAGCATAGACATCCAGATAGATAGATC") == "Charlie");
    REQUIRE(
        !db.findMatch("GGTACAGATGCAAAGATAGATAGATGTCGTCGAGCAATCGTTTCGATAATGAATGAATGAATGAATGAATGAATGACACACGTCGATGCTAGC"
                      "GGCGGATCGTATATCTATCTATCTATCTATCAACCCCTAG")
             .has_value());
}
